version: '3'
services:
  jenkins:
    image: myjenkinsimage
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home
    user: root
volumes:
  jenkins-data: